# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Cla
description: # this means to ignore newlines until "baseurl:"
  Cla's personal website
baseurl: "" # the subpath of the site
url: "https://claudia-viaro.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Bio  
    - name: Work
    - name: Tutoring

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: claudia.viaro@warwick.ac.uk
      link: mailto:yourmail@domain.com
    - name: Office
      value: Mathematical Sciences Building 3.14
      link: http://campus-cms.warwick.ac.uk/share/79487cc8472ac794747203b7e6268ab0
    - name: LinkedIn
      value: LinkedIn
      link: http://linkedin.com/in/claudia-viaro/  
  follow:
    - name: GitHub
      link: http://github.com/claudia-viaro
    - name: Spotify
      link: https://open.spotify.com/user/1184070719
    - name: WML group
      link: https://wmlg.io/
    - name: Vollmer Lab
      link: https://sebastian.vollmer.ms/people/

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
